name: LUNA Period Tracker Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run LUNA bash script
        run: bash ./scripts/my-luna-script.sh
